<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="19.03s"
		durationms="19031"
		type="root"
		rid="3228980c6b1c68e"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="WMY"
		rxversion="9.1.1.0"
		host="DESKTOP-SM51UF2"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="zh-CN"
		dtnlanguage="zh-CN"
		screenresolution="1920x1080"
		timestamp="2020/10/15 12:00:42"
		timestampiso="2020-10-15T04:00:42"
		endtime="2020/10/15 12:01:01"
		timeoutfactor="2"
		module="batchInput012">
		<detail>
			batchInput012
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:19.031"
			timeRelativeToTestModuleStartTime="00:19.031"
			timeWallClock="12:01:01"
			time="00:19.031"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
